import Head from "next/head";
import React, { useEffect, useState } from "react";
import { gsap } from "gsap";

//components
import Header from "./components/header";
import Navigation from "./components/navigation";

//pages
import HomePage from "./home";
import About from "./about";
import References from "./references";
import Contact from "./contact";
import { useIsomorphicLayoutEffect } from "@/helpers/helper/IsoMorphicEffect";

const routes = [
  { path: "/", name: "Home", Component: HomePage },
  { path: "/about", name: "About", Component: About },
  { path: "/references", name: "References", Component: References },
  { path: "/contact", name: "Contact", Component: Contact },
];

function debounce(fn, ms: number) {
  let timer;
  return () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      fn.apply(this, arguments);
    }, ms);
  };
}

export default function Home() {
  if (typeof window !== "undefined") {
    const [dimensions, setDimensions] = useState({
      height: window.innerHeight,
      width: window.innerWidth,
    });
    // prevents flashing
    gsap.to("body", { duration: 0, css: { visibility: "visible" } });

    useEffect(() => {
      // inner height of mobile devices
      let vh = dimensions.height * 0.01;
      document.documentElement.style.setProperty("--vh", `${vh}px`);

      const debouncedHandleResize = debounce(function handleResize() {
        setDimensions({
          height: window.innerHeight,
          width: window.innerWidth,
        });
      }, 1000);
      window.addEventListener("resize", debouncedHandleResize);
      return () => {
        window.removeEventListener("resize", debouncedHandleResize);
      };
    });
  }
  return (
    <>
      <Head>
        <title>ELP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <div className="App">
          <HomePage />
        </div>
        <Navigation />
      </main>
    </>
  );
}
